[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#fd267a"
backgroundColor = "#111111"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#e8e8e8"
font = "sans serif"
